### PR TITLE
Add support for Thermistor K-type with MAX6675

### PR DESCRIPTION
**Pull request by aschoelzhorn**
I added support for a thermistor K-type connected via MAX6675.
This sensors are quite cheap and have the advantage that they already come with a M3 or M4 thread, which can be used for modding the Gaggia. 
They are sold as "3D Printer Head Thermocouple" e.g. on Aliexpress or Ebay

### CODE REVIEW

**Comment by medlor** [comment]
Thanks for the PR, Alex! 

uhm.. it looks like the sensor has only a resolution of 0.25degree, a rather high accuracy of 1.5degree and could it be that the operation temperature is only supported up to 85degree celsius? https://datasheets.maximintegrated.com/en/ds/MAX6675.pdf
I assume you have tested this temp sensor and it works good enough? :-)

A poll interval of 250ms is also rather high. Since version 2 (as far as I remember) we have switched from 1sec poll-time to 0.1s. Can you tell me what the arduino library returns when readCelsius() is called every 0.1 sec? is the "old" value re-returned or does the library "hang" until the full 250ms have passed?

**Comment by medlor** [comment]
Teste doch mal bitte die 3.1.0_beta_2 aus und schau in das LOG ob da was auffaellig (negatives) passiert.
Da hab ich deine Änderungen alle drinnen.

**Comment by aschoelzhorn** [comment]
Regarding the MAX6675. Until now I didn't have any problems. The poll interval needs to be at least 250ms, currently I set it to 260ms, because with 250ms I always just get the same value. The library doesn't hang if polled too fast, it just returns always the same value value.

> In either case I propose to set refreshTempInterval=250 if TEMP_SENSOR==3 is used. I will adapt the code and push an adapted version for you to test.

Oh, I somehow missed refreshTempInterval and implemented it again for TEMP_SENSOR == 3 (just search for TEMPSENSOR_MAX6675K_MIN_DELAY)

**Comment by medlor** [comment]
I have already done all integrations in 3.1.0_beta_2. Just check if everything is working as expected.

**Pull request merged**
